### GET request to example server
GET 127.0.0.1:8000/

###

###
GET localhost:8000/users/1
###

###
POST localhost:8000/auth/token
Content-Type: application/json

{
  "username": "misha",
  "password": "12345"
}
###